<?php

namespace PaysageBundle\Repository;

/**
 * ImageChantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageChantierRepository extends \Doctrine\ORM\EntityRepository
{
}
