paysage_home:
    path:     /
    defaults:
        _controller: PaysageBundle:Paysage:index

paysage_chantier_nouveau:
    path:     /nouveau
    defaults:
        _controller: PaysageBundle:Paysage:newChantier

paysage_chantier_edit:
    path:     /edit/{id}
    defaults:
        _controller: PaysageBundle:Paysage:edit
    requirements:
            id: \d+
            format: html

paysage_chantier_view:
    path: /chantier/{id}
    defaults:
        _controller: PaysageBundle:Paysage:view
    requirements:
        id: \d+
        format: html

paysage_contact:
    path:     /contact
    defaults: { _controller: PaysageBundle:Paysage:contact }

paysage_mailsent:
    path:    /message-envoye
    defaults: { _controller: PaysageBundle:Paysage:mailsent }